CREATE LOGIN [WorldCitiesAdmin]
    WITH PASSWORD = N'{+ca|.lla$ir|gRiPzkKbsdqmsFT7_&#$!~<OshBrgray3n~', SID = 0x636598DCE78C3D4398DF6CEA3DBA2C23, DEFAULT_DATABASE = [WorldCities], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

